"""Database creation

Revision ID: 0e47c952c9ef
Revises: 
Create Date: 2024-10-01 17:38:27.787026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e47c952c9ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'athletes', 'countries', ['country_id'], ['country_id'])
    op.drop_column('athletes', 'country')
    op.drop_constraint('Countries_country_name_key', 'countries', type_='unique')
    op.add_column('events', sa.Column('olympic_id', sa.Integer(), nullable=True))
    op.alter_column('events', 'sport_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False)
    op.drop_constraint('Events_fk4', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'olympics', ['olympic_id'], ['olympic_id'])
    op.drop_column('events', 'olympics_id')
    op.alter_column('medals', 'event_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False)
    op.alter_column('medals', 'athlete_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    nullable=True)
    op.drop_constraint('Sport_sport_name_key', 'sports', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Sport_sport_name_key', 'sports', ['sport_name'])
    op.alter_column('medals', 'athlete_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    nullable=False)
    op.alter_column('medals', 'event_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.add_column('events', sa.Column('olympics_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('Events_fk4', 'events', 'olympics', ['olympics_id'], ['olympic_id'])
    op.alter_column('events', 'sport_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.drop_column('events', 'olympic_id')
    op.create_unique_constraint('Countries_country_name_key', 'countries', ['country_name'])
    op.add_column('athletes', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'athletes', type_='foreignkey')
    op.drop_column('athletes', 'country_id')
    # ### end Alembic commands ###
